/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappTemplateIndexRouteImport } from './routes/whatsapp-template.index'
import { Route as FileIndexRouteImport } from './routes/file.index'
import { Route as WhatsappTemplateTemplateIdRouteImport } from './routes/whatsapp-template.$templateId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappTemplateIndexRoute = WhatsappTemplateIndexRouteImport.update({
  id: '/whatsapp-template/',
  path: '/whatsapp-template/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileIndexRoute = FileIndexRouteImport.update({
  id: '/file/',
  path: '/file/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappTemplateTemplateIdRoute =
  WhatsappTemplateTemplateIdRouteImport.update({
    id: '/whatsapp-template/$templateId',
    path: '/whatsapp-template/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/whatsapp-template/$templateId': typeof WhatsappTemplateTemplateIdRoute
  '/file/': typeof FileIndexRoute
  '/whatsapp-template/': typeof WhatsappTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/whatsapp-template/$templateId': typeof WhatsappTemplateTemplateIdRoute
  '/file': typeof FileIndexRoute
  '/whatsapp-template': typeof WhatsappTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/whatsapp-template/$templateId': typeof WhatsappTemplateTemplateIdRoute
  '/file/': typeof FileIndexRoute
  '/whatsapp-template/': typeof WhatsappTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/whatsapp-template/$templateId'
    | '/file/'
    | '/whatsapp-template/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/whatsapp-template/$templateId'
    | '/file'
    | '/whatsapp-template'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/whatsapp-template/$templateId'
    | '/file/'
    | '/whatsapp-template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  WhatsappTemplateTemplateIdRoute: typeof WhatsappTemplateTemplateIdRoute
  FileIndexRoute: typeof FileIndexRoute
  WhatsappTemplateIndexRoute: typeof WhatsappTemplateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-template/': {
      id: '/whatsapp-template/'
      path: '/whatsapp-template'
      fullPath: '/whatsapp-template/'
      preLoaderRoute: typeof WhatsappTemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/': {
      id: '/file/'
      path: '/file'
      fullPath: '/file/'
      preLoaderRoute: typeof FileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-template/$templateId': {
      id: '/whatsapp-template/$templateId'
      path: '/whatsapp-template/$templateId'
      fullPath: '/whatsapp-template/$templateId'
      preLoaderRoute: typeof WhatsappTemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  WhatsappTemplateTemplateIdRoute: WhatsappTemplateTemplateIdRoute,
  FileIndexRoute: FileIndexRoute,
  WhatsappTemplateIndexRoute: WhatsappTemplateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
